version: "3.8"

networks:
  app-network:
services:
  server:
    build: .
    image: docker.pkg.github.com/utain/go-12factor-example/go-server:latest
    environment:
      DATABASE_URL: postgresql://example:P@55w0rd@postgres:5432/example?sslmode=disable
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:13.2
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=P@55w0rd
      - POSTGRES_USER=example
      - POSTGRES_DB=example
    networks:
      - app-network