metadata:
  servicename: server
server:
  host: localhost
  port: 5000
database:
  url: postgresql://example:P@55w0rd@localhost:5432/example?sslmode=disable
  pool:
    max: 50
otel:
  log:
    level: info
    development: false
  trace:
    proto: grpc
    endpoint: localhost:30800
